export const CAR_COLORS = [
  { color: 'Белый', value: 'grey-1' },
  { color: 'Черный', value: 'black' },
  { color: 'Темно-серый', value: 'grey-7' },
  { color: 'Серый', value: 'grey-4' },
  { color: 'Вишневый', value: 'red-10' },
  { color: 'Красный', value: 'red' },
  { color: 'Темно-синий', value: 'blue' },
  { color: 'Синий', value: 'light-blue' },
  { color: 'Темно-зеленый', value: 'teal' },
  { color: 'Зеленый', value: 'green' },
  { color: 'Коричневый', value: 'brown' },
  { color: 'Бежевый', value: 'biege' },
  { color: 'Оранжевый', value: 'orange' },
  { color: 'Желтый', value: 'yellow' },
  { color: 'Фиолетовый', value: 'purple' },
  { color: 'Розовый', value: 'pink' },
];
